### ISSUE TITLE
Question about vim and 256 colors

### ISSUE THREAD

**Issue by lukas-123** [base16-builder/base16-builder#104]
I use rxvt-unicode with 256 color support. `tputs` output is 256 as expected. `echo $TERM` outputs `rxvt-unicode-256color`. I use the following color configurations in my .Xresources file:
https://github.com/lukas-123/.dotfiles/blob/b9f8d65dbb7af91d408b0fc821f9d0521b036730/.Xresources

If I use the desert color theme it looks like this: 
![colorscheme_desert](https://cloud.githubusercontent.com/assets/11629114/15075396/6d13e662-13a4-11e6-9558-60db5256d26e.png)

A theme created with base16-builder on the other hand looks like this: 
![colorscheme_my](https://cloud.githubusercontent.com/assets/11629114/15075424/987b5060-13a4-11e6-89f5-720dd28ee7f2.png)

And like this with `let base16colorspace=256`:
![colorscheme_my2](https://cloud.githubusercontent.com/assets/11629114/15075489/ebb2e3b0-13a4-11e6-956b-950ccef6a0db.png)

Does anybody know how to fix this?

**Comment by alexbooker** [comment]
I wrote a bit about this problem [here](https://github.com/base16-builder/base16-builder/issues/82#issuecomment-202837047). 

You need to generate a  [shell](https://github.com/base16-builder/base16-builder/tree/master/db/templates/shell) theme and reference it from your shell using the instructions @chriskempson wrote [here](https://github.com/chriskempson/base16-shell#shells).

**Comment by lukas-123** [comment]
@alexbooker 
Thank you it works now. I just thought that you don't need to set the colors with base16-shell if your terminal supports 256 colors. Apparently I was wrong. 
Maybe someone could make a README or wiki entry for this case?
P.S. Your youtube tutorials are awesome :)

**Comment by aloisdg** [comment]
It could be nice to add this to the wiki/doc. ;)
