### ISSUE TITLE
Add gtk template

### ISSUE THREAD

**Issue by rosshadden** [base16-builder/base16-builder#106]
It would be awesome to have Pidgin and other gtk apps use these themes.

@manpages added a commit to the original base16-bulider [here](https://github.com/manpages/base16-builder/commit/33c8df5d299d91277dbf43a12ae6f52c0bbb0483), so at best we just need to port the `erb` template over to `ejs`.

Despite the description being "Fork of base16-builder", it's not actually a fork, and thus was never made into a PR to the original project.  That being said, it seems to have the same structure as the original project did, so hopefully the port is straightforward.

**Comment by alexbooker** [comment]
A GTK template would be awesome and the one @manpages wrote looks perfect :+1: 

@manpages, is it OK if we use the template you wrote here?

**Comment by alexbooker** [comment]
@manpages said it was cool via Twitter.

@rosshadden or @aloisdg, it would be awesome if one of you could make a pull request for this -- it's just a case of porting the template to ejs. If no one else does, I'll do it this weekend 🤗

**Comment by alexbooker** [comment]
Thank you @rosshadden  and @manpages. I made a commit: d54bb949e1d3a48fcf6a9ac772f7ca2f29e30e09. 

I also [published](https://www.npmjs.com/package/base16-builder) `0.0.31`. You can update by running **`npm install -g base16-builder`**.

**Comment by rosshadden** [comment]
Works great, thanks!
