### ISSUE TITLE
Add Oliveira scheme

### ISSUE THREAD

**Issue by protesilaos** [base16-builder/base16-builder#107]
YAML file: https://github.com/protesilaos/oliveira/blob/master/lb/oliveira.yml

**Comment by alexbooker** [comment]
Hi 👋.

Thanks for the request.

I'm taking a break from the computer today (I'm writing to you from Android), but I'll get on this tomorrow. 
In the mean time, I highly encourage you to submit a pull request. All you have to do is add the scheme you linked to [the `db/schemes`](https://github.com/base16-builder/base16-builder/tree/master/db/schemes) folder and you're good to go 👍

**Comment by aloisdg** [comment]
Hello !

@protesilaos You can submit a pull request. In case of trouble, I will be around. Feel free to summon me today ;)

**Comment by protesilaos** [comment]
Hello! Thank you both!

I think I prepared the PR the right way. Apologies for doing this on a Sunday. Did not mean to disturb you.

Also congratulations for re-launching this project. Wish you best of luck.

**Comment by alexbooker** [comment]
You're _too_ polite -- it's no bother at all :smile: 

Thank you very much for the pull request.
