### ISSUE TITLE
Cannot generate any of the Atelier Schemes

### ISSUE THREAD

**Issue by xaviervalarino** [base16-builder/base16-builder#127]
I cannot seem to generate any of the _Atelier_ color schemes. 
## Steps to reproduce
_e.g._
```sh
base16-builder -s ateliersulphurpool -t shell -b dark
base16-builder -s 'atelier sulphurpool' -t shell -b dark
```
## Expected Behaviour
Output atelier* scheme
## Actual Behaviour
Output:
```
Could  not find scheme atelier*
```
## Node and npm versions
Node v6.2.2
npm 3.9.5

## Base16-Builder version
1.2.0

**Comment by aloisdg** [comment]
Hello,

You have some errors in your command. Can you try:

    $> base16-builder -s atelier-sulphurpool -t shell -b dark

* The argument `-b` stands for brightness.
* Atelier* 's scheme use the format `atelier-{name}`

Hope it will fix your problem

**Comment by xaviervalarino** [comment]
@aloisdg Thanks, this worked!

>(I guess you know and forgot to write in your issue 😉 )

Correct, I forgot to add the `brightness` option in my example. I've gone ahead and fixed my initial comment.

The dash makes a lot of sense now that you have shown me, but maybe this caveat should be documented? Maybe under the `--help` message output or in the HTML page generated by `ls schemes`?

**Comment by aloisdg** [comment]
@xaviervalarino I think you are right. We will talk about this. 👍

**Comment by xaviervalarino** [comment]
Let me know if you need any help

**Comment by aloisdg** [comment]
@xaviervalarino Issue created #129 😉
