### ISSUE TITLE
Move from nunjucks to ejs in contributing.md 

### ISSUE THREAD

**Issue by aloisdg** [base16-builder/base16-builder#130]
## Steps to reproduce 

Navigate to [Writing a template](https://github.com/base16-builder/base16-builder/blob/master/contributing.md#writing-a-template) and read

## Expected Behaviour

A Base16-builder's template is an ejs file. Ejs is simple templating language for JavaScript. You can learn more about ejs files on their [page](https://github.com/mde/ejs).

## Actual Behaviour

A Base16-builder's template is a nunjucks file. Nunjucks is a rich and powerful templating language for JavaScript made by Mozilla. You can learn more about nunjuck files on their [page](https://mozilla.github.io/nunjucks/).

## Node and npm versions

irrelevant

## Base16-Builder version

v1.2.0

### Additional Information

Related to #70

**Comment by alexbooker** [comment]
:+1:
