### ISSUE TITLE
Neovim: Function name required

### ISSUE THREAD

**Issue by monrcelik** [base16-builder/base16-builder#135]
## Steps to reproduce 
`base16-builder -s ocean -t vim -b dark > base16-ocean-dark.vim`

## Node and npm versions
**node:** 4.4.7
**npm:** 2.15.8

## Base16-Builder version
1.2.0

### Additional Information
In neovim I'm getting this error.
![screenshot2016-08-0121 57 09](https://cloud.githubusercontent.com/assets/14337113/17305695/508cb6a2-5834-11e6-95fb-d6fb7d481b20.png)

**Comment by Probotect0r** [comment]
How are you setting the color scheme to the one generated?

**Comment by monrcelik** [comment]
I put the generated scheme into color folder. And set the colorscheme property to base16-ocean-dark.

**Comment by aloisdg** [comment]
I never used neovim. Are you sur that vim's theme are compatible with it? Can you compare a default neovim's theme with the one generated? Can you try the one generated on a classic vim?

Thank you 😄

**Comment by CrashyBang** [comment]
Hey @monrcelik can can copy and paste your `init.vim` I have been using with neovim for a couple of months and never had any issues hopefully I can compare to mine and spot the problem :).

**Comment by monrcelik** [comment]
@CrashyBang It's here. I didn't have a problem other vim themes but base16.

[init.vim.txt](https://github.com/base16-builder/base16-builder/files/436404/init.vim.txt)

**Comment by CrashyBang** [comment]
Hey @monrcelik,

Two things can you try and change:

`colorscheme base16-ocean-dark`
to
`colorscheme base16-ocean`

And can you change:

`let $NVIM_TUI_ENABLE_TRUE_COLOR=1`
to
`set termguicolors` if you want to know more about this please read [here](https://github.com/neovim/neovim/wiki/Following-HEAD#20160511)

Cheers.

**Comment by monrcelik** [comment]
Hey @CrashyBang. `set termguicolors` solved my problem. Thanks!
