### ISSUE TITLE
i3status generation error

### ISSUE THREAD

**Issue by omar-polo** [base16-builder/base16-builder#145]
The configuration for i3status isn't generated correctly. I suspect that is missing a `#` on this line: https://github.com/base16-builder/base16-builder/blob/master/db/templates/i3status/dark.ejs#L8

I haven't submit any pull request because I dunno how to test if my proposal actually works
## Steps to reproduce

```
$ base16-builder -s atelier-lakeside -t i3status -b dark
```
## Expected Behaviour

it sould print:

```
# ~/.i3status.conf
# Base16 Atelier Lakeside, by Bram de Haan (http://atelierbram.github.io/syntax-highlighting/atelier-schemes/lakeside/)
# template by Matt Parnell, @parnmatt

general {
    colors = true
    color_good = "#568c3b"
    color_bad = "#d22d72" # <- the #
    ## remember to add your prefered interval
    # interval = 5
}

## remember to add the rest of your configure

```
## Actual Behaviour

```
# ~/.i3status.conf
# Base16 Atelier Lakeside, by Bram de Haan (http://atelierbram.github.io/syntax-highlighting/atelier-schemes/lakeside/)
# template by Matt Parnell, @parnmatt

general {
    colors = true
    color_good = "#568c3b"
    color_bad = "d22d72"
    ## remember to add your prefered interval
    # interval = 5
}

## remember to add the rest of your configure
```
## Node and npm versions

node version: 6.9.1

npm version: 3.10.9
## Base16-Builder version

1.3.0

**Comment by aloisdg** [comment]
Hello,

Thank you for finding this one. The proble exist for both the [light](https://github.com/base16-builder/base16-builder/blob/master/db/templates/i3status/light.ejs) and the [dark](https://github.com/base16-builder/base16-builder/blob/master/db/templates/i3status/dark.ejs). It is an easy fix. Do you want do submit a PR yourself? 😄 

Cheers,

**Comment by omar-polo** [comment]
"detto fatto" :joy:

done!

**Comment by aloisdg** [comment]
Merged! Thank you
