### ISSUE TITLE
Scheme name is interpreted as a number for "3024"

### ISSUE THREAD

**Issue by norcalli** [base16-builder/base16-builder#147]
## Steps to reproduce 
`base16-builder -s 3024 -t termite`

## Expected Behaviour
Output a scheme for 3024 with termite

## Actual Behaviour
Errors out on `schemeNameOrPath.toLowerCase` is not a function.

I've already debugged this to be caused by `cli.flags` interpreting 3024 as a number instead of the theme name, so a simple fix is to force a string:
```node
let schemeNameOrPath = ('' + _cli$flags.scheme);
```

## Node and npm versions
`v5.12.0`, `3.8.6`, respectively.

## Base16-Builder version
`1.3.0`

**Comment by aloisdg** [comment]
Hello,

Thank you for this one!

What are the benefits of using ''+ instead of toString()? Could you open a PR with your fix?

Cheers

**Comment by norcalli** [comment]
https://github.com/base16-builder/base16-builder/pull/148
