### ISSUE TITLE
Document the template convention

### ISSUE THREAD

**Issue by alexbooker** [base16-builder/base16-builder#30]
Templates need to adhere to a certain [convention](https://github.com/alexbooker/base16-builder/issues/19#issuecomment-180026062) before _base16-builder_ can detect them.

Whilst I believe that most contributors will be able to deduce this convention by looking at the [templates](https://github.com/alexbooker/base16-builder/tree/master/db/templates) directory, it would also be beneficial to formally document the convention.

Seeing as how this information is most relevant to contributors, I think [`contributing.md`](https://github.com/alexbooker/base16-builder/tree/master/db/templates) would be a natural home for the so-called specification.

**Comment by aloisdg** [comment]
I think we shouldn't cluttered "contributing.md" with this kind of information. It belongs in a ~~Museum~~ documentation (separate file, Wiki, [Read the Docs](https://readthedocs.org)). But I will comply and add everything in this single file. At least, for now. :wink: 

related to: 

run the project: #14 
template spec: #19

**Comment by alexbooker** [comment]
@aloisdg Thank you. Like I mentioned on Gitter, I will be open to an alternative location in the future.

**Comment by aloisdg** [comment]
@alexbooker Yes. For now, it is good enough :smile:
