### ISSUE TITLE
Do not auto-escape output

### ISSUE THREAD

**Issue by alexbooker** [base16-builder/base16-builder#45]
![](http://i.imgur.com/JkpWNhw.png)

All you need to do is tell Nunjucks to not escape values. We don't care about XSS here :smirk:

**Comment by alexbooker** [comment]
Uh oh. It looks like the only way to do this is to edit the templates from

```
! Base16 {{ scheme }}
```
to

```
! Base16 {{ scheme | safe }}
```

([source](http://stackoverflow.com/questions/29866034/stop-nunjucks-from-escaping-html))

@aloisdg, do you think it'd be possible to write a small script to do this conversion automatically?

**Comment by alexbooker** [comment]
Hold the phone. [I just found this](https://mozilla.github.io/nunjucks/api.html#opts-autoescape).

**Comment by alexbooker** [comment]
Alright, think I fixed it in d910c19960b139567c969508ac907301529a8a77

**Comment by aloisdg** [comment]
Perfect! :)
