### ISSUE TITLE
Would it be a good idea to use an inline logo?

### ISSUE THREAD

**Issue by aloisdg** [base16-builder/base16-builder#52]
Hello,

I think the logo take a lot of place.
What about an inline logo?

Something like this

    { # } BASE16-BUILDER

Where `{ # }` is the logo.

**Comment by alexbooker** [comment]
This crossed my mind as well. I'll look into it. Ty.

**Comment by Phisherman** [comment]
Here you go. [logoWithTextInline.zip](https://github.com/base16-builder/base16-builder/files/133222/logoWithTextInline.zip)

**Comment by aloisdg** [comment]
@Phisherman Can you also add a png as image in your comment? It will be easiest for the discussion. Thank you.

**Comment by Phisherman** [comment]
![logowithtextinline](https://cloud.githubusercontent.com/assets/2873986/13090600/00486fe4-d4f7-11e5-9bdb-fc814a3c6e77.png)

**Comment by aloisdg** [comment]
@Phisherman If you adjust the logo to fit with the size of the title, is the logo not to small?

**Comment by Phisherman** [comment]
Mhm. I can do this. I thought that this would be more appreciated.

**Comment by aloisdg** [comment]
@Phisherman  I completely agree to use one you posted. I ask for another export by curiosity. I let @alexbooker have the last word :smile:

**Comment by Phisherman** [comment]
Haha, ok! Here is the old one with changed text orientation. If you like that I'll send you the rest.

![logowithtextinline](https://cloud.githubusercontent.com/assets/2873986/13090836/571425c4-d4f8-11e5-9393-268c5d8e3ebc.png)

**Comment by aloisdg** [comment]
@Phisherman My bad, I wasn't clear. I thought about adjusting the size vertically. The logo would have the same height than the current text. By the way, you got there another nice idea :)

**Comment by Phisherman** [comment]
@aloisdg
Like that?

![logowithtextinline](https://cloud.githubusercontent.com/assets/2873986/13091099/cdb94438-d4f9-11e5-9a30-9b11e75aba2c.png)

**Comment by aloisdg** [comment]
@Phisherman Yes thats my idea. At the end you were right. The first one is my favorite. Thank you for your dedication!

**Comment by Phisherman** [comment]
@aloisdg OK.

**Comment by alexbooker** [comment]
Closed in 375d29a8df87ac3414695b2430090564f7cc7973.

Thank you, both.

@Phisherman, could you please send a pull request adding those files to the `media` directory? If you don't want to, I'll do it tomorrow. Thanks.
