### ISSUE TITLE
Make "-h" the default output

### ISSUE THREAD

**Issue by aloisdg** [base16-builder/base16-builder#54]
Hello,

When we run `base16-builder` without any arguments a "fatal" error is thrown:

    fatal: You did not supply valid arguments. Run \'base16-builder -h\' for guidance.

I think it would be better to make the "-h" a default and to print it when no argument is given. It is the choice made by "git" or "npm" for example.

Cheers,

**Comment by alexbooker** [comment]
Sounds good.

**Comment by aloisdg** [comment]
Yes but if you want to do it, you can change it. :)

**Comment by alexbooker** [comment]
@aloisdg It'll take two seconds.

**Comment by aloisdg** [comment]
Ok do it I finish my template :)
