### ISSUE TITLE
Add support for VSCode

### ISSUE THREAD

**Issue by aloisdg** [base16-builder/base16-builder#55]
Hello,

Visual Studio Code support Textmate theme but it could be better with some adjustment.
I am looking for a better support. VSCode is shiped with an implementation of Solarized. It could be nice to use it as a bridge for the port.

Cheers,

**Comment by alexbooker** [comment]
:+1:

**Comment by aloisdg** [comment]
@alexbooker I finished it and I am testing it right now ;)
