### ISSUE TITLE
Do we have a specific code guidelines to follow?

### ISSUE THREAD

**Issue by aloisdg** [base16-builder/base16-builder#57]
Hello,

Everything is in the title.
We have a .eslintrc but it is a bit light.

Thank you

**Comment by alexbooker** [comment]
I think what we have is fine for now.

**Comment by aloisdg** [comment]
It could be nice to add one to the contributing.md. It is not mandatory. So we can just close this and follow our own path.

**Comment by alexbooker** [comment]
@aloisdg I think this module is - and always will be - too simple to warrant a strict code style. It just introduces the barrier to entry, in my opinion.

**Comment by aloisdg** [comment]
@alexbooker good point. Lets close this for now.
