### ISSUE TITLE
Add Wox template

### ISSUE THREAD

**Issue by aloisdg** [base16-builder/base16-builder#59]
Hello,

Wox is an effective launcher for Windows. You can learn more about the project on its [repository](https://github.com/Wox-launcher/Wox).

Right now, I have the support for the dark and the light template (here with the solarized scheme):

![dark](https://cloud.githubusercontent.com/assets/3449303/13378673/a9b3778c-de33-11e5-8cae-9e6cefbd1772.PNG)

![light](https://cloud.githubusercontent.com/assets/3449303/13378741/a74d1ac8-de35-11e5-87a3-01e45a5106ef.PNG)

I created them with wox's [theme builder](http://www.getwox.com/theme/builder) with inspiration from Alfred ([1](http://www.alfredforum.com/topic/455-solarized-dark/) [2](https://github.com/imkmf/alfred-solarized) [3](https://github.com/timbuchwaldt/alfred-solarized) [4](http://www.chadkouse.com/2013/03/solarized-theme-for-alfred-v2.html)). I chose `0A` as accent color but any accent color will fit (I found `0C` really convenient too).

**Comment by alexbooker** [comment]
Sounds awesome. 

If we can make this happen, it'll make this tool *much* more compelling for Windows users.

**Comment by aloisdg** [comment]
@alexbooker 

Thank you. I added the light theme too :) (Lumosh powa \o/)

**Comment by aloisdg** [comment]
More pics

Paraiso:

![paraiso](https://cloud.githubusercontent.com/assets/3449303/13379086/c56910d6-de42-11e5-9676-c2d7fa2625c4.PNG)

Flat:

![flat](https://cloud.githubusercontent.com/assets/3449303/13379088/ca8145de-de42-11e5-99b1-19060eedfc11.PNG)

**Comment by aloisdg** [comment]
I need schemer to run them all! ;)
