### ISSUE TITLE
Should we improve the label system?

### ISSUE THREAD

**Issue by aloisdg** [base16-builder/base16-builder#63]
Hello,

Today, @alexbooker adds more labels to the project. I think we can try to enhance the label system.
I read about [gitlabel](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63#.rq2rkybda) last week. Gitlabel is made by @himynameisdave and is hosted [here](https://github.com/himynameisdave/git-labelmaker).

What do you think of this system?

**Comment by alexbooker** [comment]
To be honest, labels are just noise right now. I'm going to remove them all except `help wanted`.

**Comment by alexbooker** [comment]
Ah. That is so much better. Thanks for reminding me.

**Comment by aloisdg** [comment]
So lets give a shot to gitlabel?

**Comment by alexbooker** [comment]
@aloisdg I don't feel the need for labels at this time. If issues ever become hard to manage, I will revisit this.

**Comment by aloisdg** [comment]
I love labels. I use them in almost all personnal projects. We cannot create group without them.

**Comment by alexbooker** [comment]
@aloisdg I am more than happy to consider gitlabel later down the line. At the moment I feel like too many labels is a  novelty.

You'll notice that I did keep the **help wanted** and **future?** labels.

**Comment by himynameisdave** [comment]
Yeah @aloisdg, organization is just a silly novelty. Why would you ever want a [sane system for organizing your projects](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63) when **help wanted** and **future?** perfectly describe the status, type and priority of every issue in this project?

**Comment by aloisdg** [comment]
Even the old github system is fine for me.

**Comment by alexbooker** [comment]
Now a few template requests are popping up I have added a **template request** label.
