### ISSUE TITLE
Error when building smartftp template

### ISSUE THREAD

**Issue by alexbooker** [base16-builder/base16-builder#67]
```
$ ./dist/cli.js -s gooey -t smartftp -b dark

Unexpected error: {"name":"Template render error"}
undefined
```

When building the `smartftp` template, I get an error. The template is clearly malformed. @aloisdg, might you know what the problem here is?

**Comment by aloisdg** [comment]
I just looked. I didnt see any problem with smartftp's templates.

**Comment by alexbooker** [comment]
@aloisdg I haven't had time to look into it properly. I just know that when I run the above command, I get an error :confused: 

Let me know what you find. If it's not a problem with the template, it could be a problem with my code. Thank you :smile:!!

**Comment by alexbooker** [comment]
I know that if you remove expresions like this one:

```
base["05"]["hex"].match(/.{2}/g).reverse().join('') 
```

... The template doesn't cause an error.

I'm not sure why expressions like that one are causing Nunjucks to chuck a wobbly because it's valid JavaScript:

```
> const color = "#ffffff"
undefined
> color
'#ffffff'
> color.match(/.{2}/g)
[ '#f', 'ff', 'ff' ]
> color.match(/.{2}/g).reverse()
[ 'ff', 'ff', '#f' ]
> color.match(/.{2}/g).reverse().join()
'ff,ff,#f'
> 
```

**Comment by aloisdg** [comment]
If the bug come from nunjucks, we should open an issue in their repository.

While there isn't a fix from them or us, we should move smartftp in a separate 'fix-smartftp' branch.

**Comment by alexbooker** [comment]
> If the bug come from nunjucks, we should open an issue in their repository.

If I'm honest, I doubt it's a problem with Nunjucks.

> While there isn't a fix from them or us, we should move smartftp in a separate 'fix-smartftp' branch.

I agree but it'll probably be quicker to just fix the bug. I won't have time to do either until tomorrow.

**Comment by alexbooker** [comment]
So, I did some experimentation and it turns out you Nunjucks **won't** evaluate arbitary expressions like `base["05"]["hex"].match(/.{2}/g)...`. It'll only evaluate simple expressions like `1 + 1`.

Aside from basic expressions, Nunjucks will only interpret pre-defined [filters](https://mozilla.github.io/nunjucks/templating.html#builtin-filters). For example, you cannot write `{{ "HI".toLowerCase }}` - that would cause a _"Template render error"_  - but you can write `{{ "HI" | lower }}`. 

**This is a big problem.** If we're lucky, [Swig](http://paularmstrong.github.io/swig/) - which has almost identical syntax to Nunjucks - will work. **If** it does, we can swap Nunjucks for Swig easily. If not, all of the templates will need converting to work with [EJS](http://www.embeddedjs.com/) or something which is a big job. Another option would be to write our own mini template engine -- that is feasible,  but that is just as much work, if not more.

**Comment by alexbooker** [comment]
I just tried and Swig doesn't support this.

**Comment by aloisdg** [comment]
If we use ejs, we are almost compatible with the old project. This is nice. We have to move from ruby to js, but for most templates we just have to remove the `@` before base.

**Comment by alexbooker** [comment]
@aloisdg Would you be willing to write a small script to do that if I change the core?

**Comment by aloisdg** [comment]
@alexbooker Sure, but I dont now when. I still dont have my computer and I am still traveling.

**Comment by aloisdg** [comment]
@alexbooker Sure, but I dont now when. I still dont have my computer and I am still traveling.

**Comment by alexbooker** [comment]
@aloisdg :smile: :+1:

**Comment by alexbooker** [comment]
This is fixed now.
