### ISSUE TITLE
Slug variable support

### ISSUE THREAD

**Issue by atelierbram** [base16-builder/base16-builder#68]
Is there, or will there be support for the "slug" variable, like in the original Base16-Builder?
(_In which the `{{ slug }}` transforms the name of the color-scheme to lowercase, and allows this to be used like that in templates like, for example, had been done in the template for CodeMirror._)

Have searched the tests and issues, but can't seem to find documentation on any clear reference to this, but maybe I'm overlooking something. 

If there is, or will be, support for this, should this, or could this be used in a command, or just work _"out of the box"_?

**Comment by alexbooker** [comment]
I must confess I wasn't aware of this `slug` variable until now so no, there isn't **currently** support for it. I think it's something we should support, though. What do you think, @aloisdg?

I can see that the [codemirror template](https://github.com/base16-builder/base16-builder/blob/master/db/templates/codemirror/dark.nunjucks) references the `slug` variable. That is a [logic error](https://en.wikipedia.org/wiki/Logic_error) and I will file a separate issue for it.

**Comment by aloisdg** [comment]
I talked about slug when I converted all templates. Vim use it too. Since you didn't comment about it, I assumed it was supported.

**Comment by aloisdg** [comment]
I think we should support it :)

**Comment by alexbooker** [comment]
@aloisdg I believe you. There was a lot of information to follow and I'm not surprised I missed something. 

Anyone want to take a stab at this? I'll be more than happy to offer my time and guidance.

**Comment by alexbooker** [comment]
Should be fixed now. Please confirm.
