### ISSUE TITLE
Rename slug to scheme-slug or something more descriptive like that

### ISSUE THREAD

**Issue by alexbooker** [base16-builder/base16-builder#76]

**Comment by aloisdg** [comment]
It is an ["official" name](https://en.m.wikipedia.org/wiki/Semantic_URL#Slug).

I would love if we can remove it and have all name usable directly as slug.

**Comment by alexbooker** [comment]
> I would love if we can remove it and have all name usable directly as slug.

What do you mean?

**Comment by aloisdg** [comment]
Slug is an human compliant name. I would love if all our names were directly human compliant.
