### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by paranoida** [base16-builder/base16-builder#77]
Hey,

Could you also push latest version to npm? Current version there is `0.0.18` (`0.0.20` on github).

Cheers,
Rafal

**Comment by alexbooker** [comment]
Hi @paranoida,

I just published the latest version. Thanks :smile:.

**Comment by alexbooker** [comment]
I just noticed the module isn't working due to a missing dependency. Hold on one second.

**Comment by alexbooker** [comment]
Fixed.

**Comment by paranoida** [comment]
Works like a charm.

Thanks
