### ISSUE TITLE
Add support for tmux, dunst and pentadactyl

### ISSUE THREAD

**Issue by aleprovencio** [base16-builder/base16-builder#82]
Sorry about this long and selfish request :)

**Comment by alexbooker** [comment]
There's no need to be sorry -- template requests are very welcome :smile:!

Could you please close this issue and create 3 separate issues for each template? I'll add the **help wanted** label to each of them. Having separate issues will make the issues easier to digest and will streamline communication.

I'll be straight-up with you. Because I have no need for these templates myself it's unlikely that I'll work on them.

**Comment by aleprovencio** [comment]
Sure, thank you!

**Comment by alexbooker** [comment]
Nice one :smile: 

Do you have any interest in contributing any of these templates? I'll be happy to answer any questions you might have.

**Comment by aleprovencio** [comment]
@alexbooker, I do have experience in other programming tools but I have to say that although there might have no need of javascript for template development, my knowledge on it is low, and even worse when talking about colors...maybe that's why I ended up using your awesome tool :D
I'm usually very busy also, but I cannot say I'm not interested in learning this color magic you use. Maybe you can suggest me some introductory material, but don't be hesitant to say if I don't meet your expectations for the task.

**Comment by aloisdg** [comment]
> Maybe you can suggest me some introductory material, but don't be hesitant to say if I don't meet your expectations for the task.

Since the wox template, I think about a tutorial "how to create a new template". I am far from good with this, but it is better than nothing. Also, we could enhance the tutorial later.

**Comment by alexbooker** [comment]
@aleprovencio You should give it a shot :+1: I think you'll be surprised at how intuitive it is. 

Maybe start with the simplest template, which is _probably_ Dunst.

@aloisdg That would be awesome :smile:

**Comment by aleprovencio** [comment]
Please tell me if I should put this question anywhere else, I need to understand some things first before working on these themes:

* For now based on `gooey dark` scheme I have generated themes only for `rxvt-unicode` and `i3` and `zathura`, but let's only talk about the first. As I run my `vim` instances under `urxvtc` It seems that the colors on it are fine using the default colorscheme. I've tried generating a theme for `vim` but it seems I need `base16-shell` installed and it seems to overlap the `rxvt-unicode` theme, so I'm confused. Can you please shed a light on this?

**Comment by alexbooker** [comment]
I'm not intimate with the details, but if you enable 256 colors in Vim, your Vim theme can look like this:

![](https://camo.githubusercontent.com/21256df57a7feaa78b9f8e1ea8b42b45fc2ab40b/68747470733a2f2f7261772e6769746875622e636f6d2f63687269736b656d70736f6e2f6261736531362d76696d2f6d61737465722f776974682d626173653136636f6c6f7273706163652d3235362d776974686f75742d6261736531362d7368656c6c2e706e67)

[According to Chris, the solution is to install a shell theme:](https://github.com/chriskempson/base16-vim#blue-line-numbers)

> If your Vim looks like the above image you are setting `let base16colorspace=256` in your ~/.vimrc but either not running Base16 Shell or Base16 Shell is not working for your terminal.

According to [this repo](https://github.com/chriskempson/base16-shell), base16 shell is...

> A shell script to change your shell's default ANSI colors but most importantly, colors 17 to 21 of your shell's 256 colorspace (if supported by your terminal). This script makes it possible honor the original bright colors of your shell (e.g. bright green is still green and so on) whilst providing the additional base16 colors to applications such as Vim.

It is also [noted](https://github.com/chriskempson/base16-shell#use-cases) that some people...

> prefer to use a script instead of a terminal emulator theme to color your shell.

If you look at the [source for the shell template](https://github.com/base16-builder/base16-builder/blob/master/db/templates/shell/dark.ejs#L13) you can see it fundamentally sets colors. 

**If you use a shell theme you _probably_ do not need a `rxvt-unicode` theme.** Of course, if you load a new shell (`fish`, `zsh`, `bash`) you'll see the default terminal window colours.

I hope that answers your question...?

**Comment by aleprovencio** [comment]
This is some clarifying material, thanks @alexbooker!
From your explanation it seems I don't really need `base16-shell` since I opted to use `rxvt-unicode` colors and my `vim` colors are not messed up like the one on the picture even using `t_Co=256`. However this way I am not able to use the `vim` template generated theme because it seems to depend on `base16-shell`, so I don't know how different that setup might be compared to what I'm using, but making that test is not that hard though.

**Comment by alexbooker** [comment]
@aleprovencio A _Vim_ theme is **not** dependent on a _shell_ theme. Why do you think it is?

**Comment by aleprovencio** [comment]
You are right, it is not. I said that because I loaded the generated colorscheme and it raised some errors, than I quickly glanced the source and saw references to base16-shell so that's where the confusion started. I'm creating an issue about the problem, and posting an Pull Request for your review.

However I still think the default colorscheme along with the `rxvt-unicode` theme under the hood looks nicer than the `vim` theme, so I'll stick to what I was using. Later we can also think about improving the `vim` theme to look better.

Another thing I noticed is that the templates should have more consistent colors related to each other, for instance the statusbar colors for the `vim` template uses a different color than the one used by the statusbar of the `zathura` template.

**Comment by alexbooker** [comment]
I see :confused: 

> Another thing I noticed is that the templates should have more consistent colors related to each other, for instance the statusbar colors for the vim template uses a different color than the one used by the statusbar of the zathura template.

That is definitely something worth exploring.

**Comment by aleprovencio** [comment]
@alexbooker is there a methodology for choosing colors when building a new template (like based on another template) or it's just a matter of what looks better?

**Comment by alexbooker** [comment]
I think it's a matter of what looks best but if I'm honest, I've never built a template...

@aloisdg has and might be able to provide some more insight.

**Comment by aleprovencio** [comment]
@alexbooker you might have never built a template but I'm very satisfied using the killer combination of `gooey` scheme from `base16` along with `arc dark GTK` which you showed off on r/unixporn once. You got that combination from the "what looks best" approach?

**Comment by alexbooker** [comment]
@aleprovencio Oh, yes. Absolutely.
