### ISSUE TITLE
fix zathura dark template

### ISSUE THREAD

**Issue by aleprovencio** [base16-builder/base16-builder#86]
I think `inputbar-fg` should be set to `base05` instead of `base02`, and I also miss `index-active-bg` which is probably `base0D`. I can make a PR if you want.

**Comment by alexbooker** [comment]
@aleprovencio I do not use _zathura_. Would you mind sending a pull request for this?

**Comment by aleprovencio** [comment]
https://github.com/base16-builder/base16-builder/pull/87 created

**Comment by alexbooker** [comment]
Closed by #87
